#!/usr/bin/python3

# Simple script for creating link files in webserver
# Rewrite LOCATION constant if you want to save files into different folder

import argparse
import os.path
import random
import string

# Defaults
LOCATION="/var/www/html"

# Parse arguments from commandline
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("link", nargs=1, help="Link to share")
    parser.add_argument("--location", default=LOCATION, help="Overrides default webserver location", required=False)
    parser.add_argument("--name", default="", help="Specifies name of link on webserver (random if empty)", required=False)
    return parser.parse_args()

# Generates 6 long unique (in folder) string from uppercase letters and numbers
def parse_name(argument, location):
    if len(argument) < 1:
        while True:
            randomized = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
            path = os.path.join(location, randomized)
            if not os.path.exists(path):
                return randomized
    else:
        return argument


def main():
    # Prepare arguments
    args = parse_args()
    link = args.link[0]
    location = args.location
    arg_name = args.name
    name = parse_name(arg_name, location)

    # Prepare pattern
    pattern = """
    <html>
        <head>
            <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
            <meta http-equiv="Pragma" content="no-cache" />
            <meta http-equiv="Expires" content="0" />
            <meta http-equiv="cache-control" content="max-age=0" />
            <meta http-equiv="cache-control" content="no-store" />
            <meta http-equiv="expires" content="-1" />
            <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
            <meta http-equiv="refresh" content="0; url="%s">
            <meta http-equiv="pragma" content="no-cache" />
            <title></title>
            <style>
                body {
                    display: none;
                }
            </style>
            <script type="text/javascript">
                window.onload = function() { 
                    var url = "%s";  
                    window.location.replace(url); 
                }
            </script>
        </head>
        <body>
            Hello terminal user :)
        </body>
    </html>""" % (link, link)

    # Check if PATH to save location exist and its writeable
    if not os.path.exists(location):
        print("Save location does not exist!")
        return
    if not os.access(location, os.W_OK):
        print("Save location is not writeable!")
        return

    # Check if file exist already - if exist append a counter
    filepath = os.path.join(location, name)
    counter = 1
    while True:
        if not os.path.exists(filepath):
            break
        filepath = "%s_%d" % (filepath, counter)
        counter = counter + 1
    
    # Create a file and write a data
    with open(filepath, "w", encoding="utf-8") as writer:
        writer.write(pattern)
    

if __name__ == "__main__":
    main()
